image: python:3.7-stretch

stages:
  - test
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

unit_test:
  stage: test
  script:
    - pytest

zip_files:
  stage: build
  script:
    - apt-get install zip
    - zip deploy/calculator-bff.zip lambda_function.py -r logic -i '*.py'

update_lambda_function:
  stage: deploy
  script:
    - pip install awscli
    - aws lambda update-function-code --function-name calcCpfContribution --zip-file fileb://deploy/calculator-bff.zip
    - aws lambda update-function-code --function-name calcCpfAllocation --zip-file fileb://deploy/calculator-bff.zip
    - aws lambda update-function-code --function-name calcCpfProjection --zip-file fileb://deploy/calculator-bff.zip
  only:
    - master