image: python:3.7-stretch

stages:
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

unit_test:
  stage: test
  allow_failure: false
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
  script:
    - pip install -r requirements-dev.txt
    - mkdir logs
    - pytest

update_lambda_function:
  stage: deploy
  only:
    - master
  before_script:
    - apt-get update
    - apt-get install -y zip
    # install external dependencies
    - pip install --target ./package -r requirements.txt
    - cd package
    - zip -r9 ${OLDPWD}/calculator-bff.zip .
    - cd $OLDPWD
    # add files from /app folder and update Lambda functions
    - zip -g calculator-bff.zip lambda_function.py -r app -i '*.py'
  script:
    - pip install awscli
    - aws lambda update-function-code --function-name calcCpfContribution --zip-file fileb://calculator-bff.zip
    - aws lambda update-function-code --function-name calcCpfAllocation --zip-file fileb://calculator-bff.zip
    - aws lambda update-function-code --function-name calcCpfProjection --zip-file fileb://calculator-bff.zip
