image: python:3.7-alpine

stages:
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

unit_test:
  stage: test
  allow_failure: false
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
  script:
    - pip install -r requirements-dev.txt
    - mkdir logs
    - pytest

update_lambda_function:
  stage: deploy
  only:
    - master
  before_script:
    - apk update && apk add zip
    # install external dependencies
    - pip install --target ./package -r requirements.txt
    - cd package
    - zip -r9 ${OLDPWD}/calculator-bff.zip . -i .
    - cd $OLDPWD
    - zip -g calculator-bff.zip lambda_function.py -r logic utils -i '*.py'
  script:
    - pip install awscli
    - aws lambda update-function-code --function-name cpfContribution --zip-file fileb://calculator-bff.zip
    - aws lambda update-function-code --function-name cpfAllocation --zip-file fileb://calculator-bff.zip
    - aws lambda update-function-code --function-name cpfProjection --zip-file fileb://calculator-bff.zip
