image: python:3.7-alpine

stages:
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

unit_test:
  stage: test
  allow_failure: false
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
  script:
    - pip install -r requirements-dev.txt
    - mkdir logs
    - pytest

deploy_staging:
  image: node:13.1-alpine
  stage: deploy
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install --save-dev serverless-offline
  script:
    - sls deploy --stage staging --verbose
