image: python:3.7-stretch

stages:
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

unit_test:
  stage: test
  script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements-dev.txt
    - mkdir logs
    - pytest

update_lambda_function:
  stage: deploy
  script:
    - apt-get update
    - apt-get install -y zip
    - pip install --target ./package -r requirements.txt
    - cd package
    - zip -r9 ${OLDPWD}/calculator-bff.zip .
    - cd $OLDPWD
    - zip -g calculator-bff.zip lambda_function.py -r config logic logs utils -i '*.py' '*.yaml' '*.log'
    - pip install awscli
    - aws lambda update-function-code --function-name calcCpfContribution --zip-file fileb://calculator-bff.zip
    - aws lambda update-function-code --function-name calcCpfAllocation --zip-file fileb://calculator-bff.zip
    - aws lambda update-function-code --function-name calcCpfProjection --zip-file fileb://calculator-bff.zip
  only:
    - master