service: calculator

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  memorySize: 128

package:
  exclude:
    - ./**
  include:
    - handler.py
    - logic/**/*.py
    - utils/**/*.py

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 5100

functions:
  cpfContribution:
    handler: handler.main
    events:
      - http: POST /cpf/contribution
  cpfAllocation:
    handler: handler.main
    events:
      - http: POST /cpf/allocation
  cpfProjection:
    handler: handler.main
    events:
      - http: POST /cpf/projection
