version: 1

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  error:
    format: '%(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcNae)s(): %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: standard
    filename: tmp/output.log
    maxBytes: 10485760
    backupCount: 10
    encoding: utf8

root:
  level: DEBUG
  handlers: [console]

loggers:
  logic.cpf:
    level: DEBUG
    handlers: [console, file]
    propagate: no