###############################################################################
#                                  PARAMETERS                                 #
###############################################################################

# CPF
PARAM_SALARY = 'salary'
PARAM_BONUS = 'bonus'
PARAM_AGE = 'age'
PARAM_DOB = 'dob'
PARAM_PERIOD = 'period'
PARAM_BONUS_MONTH = 'bonus_month'
PARAM_YOY_INCREASE_SALARY = 'yoy_increase_salary'
PARAM_BASE_CPF = 'base_cpf'
PARAM_N_YEARS = 'n_years'
PARAM_TARGET_YEAR = 'target_year'
PARAM_ACCOUNT_DELTAS = 'account_deltas'

# Housing
PARAM_PROPERTY_TYPE = 'property_type'
PARAM_FIXED_INCOME = 'fixed_income'
PARAM_VARIABLE_INCOME = 'variable_income'
PARAM_PROPERTY_LOANS = 'property_loans'
PARAM_PROPERTY_LOANS_GUARANTOR = 'property_loans_guarantor'
PARAM_OTHER_LOANS = 'other_loans'
# HDB
PARAM_APPL_PERIOD = 'application_period'
PARAM_FLAT_TYPE = 'flat_type'
PARAM_PROFILE = 'profile'
PARAM_INCOME = 'income'
PARAM_ESTATE = 'estate'
PARAM_FLAT_SIZE = 'flat_size'
PARAM_NEAR_PARENTS = 'near_parents'

###############################################################################
#                                     GENERAL                                 #
###############################################################################

AGE = 'age'
ALL_LOANS = 'all_loans'
ALL_PROPERTY_LOANS = 'all_property_loans'
ALLOCATION = 'allocation'
ANNUALLY = 'annually'
AMOUNT = 'amount'
BEFORE_SEP_2019 = 'before_sep_2019'
BODY = 'body'
BTO = 'bto'
COMBINED = 'combined'
CONTRIBUTION = 'contribution'
CONT_EMPLOYEE = 'cont_employee'
CONT_EMPLOYER = 'cont_employer'
DELTAS = 'deltas'
DURATION = 'duration'
EMPLOYEE = 'employee'
EFFECTIVE_INCOME_LEVEL = 'effective_income_level'
ELIGIBILITY = 'eligibility'
ERROR = 'errors'
FINAL = 'final'
FREQUENCY = 'frequency'
IS_SA_TOPUP_FROM_OA = 'is_sa_topup_from_oa'
MA = 'ma'
MA_INTEREST = 'ma_interest'
MA_TOPUP = 'ma_topup'
MA_WITHDRAWAL = 'ma_withdrawal'
MATURE = 'mature'
MAX_MORTGAGE = 'max_mortgage'
MAX_MORTGAGE_MSR = 'max_mortgage_msr'
MAX_MORTGAGE_TDSR = 'max_mortgage_tdsr'
MISC = 'misc'
MONTH = 'month'
MONTHLY = 'monthly'
MSR = 'MSR'
NO = 'no'
NONMATURE = 'nonmature'
OA = 'oa'
OA_INTEREST = 'oa_interest'
OA_TOPUP = 'oa_topup'
OA_WITHDRAWAL = 'oa_withdrawal'
PARAMS = 'params'
PATH = 'path'
PCT_OF_SALARY = 'pct_of_salary'
PERIOD = 'period'
RATES = 'rates'
RATIO = 'ratio'
RECURRENCE = 'recurrence'
REMARKS = 'remarks'
RESALE = 'resale'
RESULTS = 'results'
SA = 'sa'
SA_INTEREST = 'sa_interest'
SA_TOPUP = 'sa_topup'
SA_WITHDRAWAL = 'sa_withdrawal'
SEP_2019_ONWARDS = 'sep_2019_onwards'
SCHEMES = 'schemes'
STATUSCODE = 'statusCode'
TDSR = 'TDSR'
TYPE = 'type'
VALUES = 'values'
VARIABLES = 'variables'
WITH_BONUS = 'with_bonus'
WITHOUT_BONUS = 'without_bonus'
YEAR = 'year'
YES = 'yes'
