###############################################################################
#                                  PARAMETERS                                 #
###############################################################################

PARAM_SALARY = 'salary'
PARAM_BONUS = 'bonus'
PARAM_AGE = 'age'
PARAM_DOB = 'dob'
PARAM_PERIOD = 'period'
PARAM_BONUS_MONTH = 'bonus_month'
PARAM_YOY_INCREASE_SALARY = 'yoy_increase_salary'
PARAM_BASE_CPF = 'base_cpf'
PARAM_N_YEARS = 'n_years'
PARAM_TARGET_YEAR = 'target_year'
PARAM_ACCOUNT_DELTAS = 'account_deltas'
PARAM_OA_TOPUPS = 'oa_topups'
PARAM_OA_WITHDRAWALS = 'oa_withdrawals'
PARAM_SA_TOPUPS = 'sa_topups'
PARAM_SA_WITHDRAWALS = 'sa_withdrawals'
PARAM_MA_TOPUPS = 'ma_topups'
PARAM_MA_WITHDRAWALS = 'ma_withdrawals'

###############################################################################
#                                     GENERAL                                 #
###############################################################################

ALLOCATION = 'allocation'
AGE = 'age'
AMOUNT = 'amount'
BODY = 'body'
COMBINED = 'combined'
CONTRIBUTION = 'contribution'
CONT_EMPLOYEE = 'cont_employee'
CONT_EMPLOYER = 'cont_employer'
DELTAS = 'deltas'
EMPLOYEE = 'employee'
ERROR = 'errors'
FINAL = 'final'
IS_SA_TOPUP_FROM_OA = 'is_sa_topup_from_oa'
MA = 'ma'
MA_INTEREST = 'ma_interest'
MA_TOPUP = 'ma_topup'
MA_WITHDRAWAL = 'ma_withdrawal'
MISC = 'misc'
MONTH = 'month'
OA = 'oa'
OA_INTEREST = 'oa_interest'
OA_TOPUP = 'oa_topup'
OA_WITHDRAWAL = 'oa_withdrawal'
PARAMS = 'params'
PATH = 'path'
PCT_OF_SALARY = 'pct_of_salary'
PERIOD = 'period'
RATES = 'rates'
RATIO = 'ratio'
RESULTS = 'results'
SA = 'sa'
SA_INTEREST = 'sa_interest'
SA_TOPUP = 'sa_topup'
SA_WITHDRAWAL = 'sa_withdrawal'
STATUSCODE = 'statusCode'
TYPE = 'type'
VALUES = 'values'
WITH_BONUS = 'with_bonus'
WITHOUT_BONUS = 'without_bonus'
YEAR = 'year'
