###############################################################################
#                                  PARAMETERS                                 #
###############################################################################

PARAM_SALARY = 'salary'
PARAM_BONUS = 'bonus'
PARAM_AGE = 'age'
PARAM_DOB = 'dob'
PARAM_PERIOD = 'period'
PARAM_BONUS_MONTH = 'bonus_month'
PARAM_YOY_INCREASE_SALARY = 'yoy_increase_salary'
PARAM_BASE_CPF = 'base_cpf'
PARAM_N_YEARS = 'n_years'
PARAM_TARGET_YEAR = 'target_year'
PARAM_OA_TOPUPS = 'oa_topups'
PARAM_OA_WITHDRAWALS = 'oa_withdrawals'
PARAM_SA_TOPUPS = 'sa_topups'
PARAM_SA_WITHDRAWALS = 'sa_withdrawals'
PARAM_MA_TOPUPS = 'ma_topups'
PARAM_MA_WITHDRAWALS = 'ma_withdrawals'

###############################################################################
#                                     GENERAL                                 #
###############################################################################

ALLOCATION = 'allocation'
AMOUNT = 'amount'
BODY = 'body'
COMBINED = 'combined'
CONTRIBUTION = 'contribution'
CONT_EMPLOYEE = 'cont_employee'
CONT_EMPLOYER = 'cont_employer'
EMPLOYEE = 'employee'
ERROR = 'errors'
FINAL = 'final'
IS_SA_TOPUP_FROM_OA = 'is_sa_topup_from_oa'
MA = 'ma'
MA_INTEREST = 'ma_interest'
MISC = 'misc'
MONTH = 'month'
OA = 'oa'
OA_INTEREST = 'oa_interest'
PARAMS = 'params'
PATH = 'path'
RATES = 'rates'
RESULTS = 'results'
SA = 'sa'
SA_INTEREST = 'sa_interest'
STATUSCODE = 'statusCode'
VALUES = 'values'
YEAR = 'year'
